### ISSUE TITLE
EntryModellable doesn't properly synthesize lists.

### ISSUE THREAD

**Issue by bennichols** [contentful/contentful.swift#132]
> - contentful.swift version number: 0.9.3
> - Xcode version number: 9.0
> - Target operating system(s) and version number(s)
    - [x ] iOS: 
    - [ ] tvOS: 
    - [ ] watchOS:
    - [ ] macOS:
> - Package manager:
    - [x ] Carthage
    - [ ] Cocoapods

When I have a list of objects or assets, they don't synthesize to the associated objects in my models. I believe this is due to the way the `relationshipNames` function is determining what is a valid relationship and not taking arrays into account. I tried to fix it there, but it didn't seem to work. Maybe there is more going on in the cache in order to get the models into the arrays?

**Comment by loudmouth** [comment]
Hey @bennichols thanks for you patience in me getting to this. In the past week, I have been working on a refactor of the mechanism to decode user-defined types. In the currently released version of contentful.swift, the SDK actually serializes in 2 steps: first to `Entry`s and `Asset`s and then to user-defined types. This is obviously inefficient. My refactor will cut out the first step to directly serialize user-defined types from JSON.

The other exciting improvement is that instead of implementing two methods like in `EntryModellable` the new system directly leverages the `Decodable` protocol that is standard lib in Swift 4 with a special method to serialize links. I will make sure to test serializing links that point to arrays and ensure that this is working with this set of upcoming changes.
