### ISSUE TITLE
Crash on simple QUERY

### ISSUE THREAD

**Issue by Ruckt** [contentful/contentful.swift#170]
HI,
I'm trying to use your SDK - 1.0.1 - and along with the issues pointed out previously that I'm encountering, I'd like to use `fetchMappedEntries` with either `MixedMappedArrayResponse` or `MappedArrayResponse` to get all entries I have and sort them into the `EntryDecodable` models I'm creating.  

So i'd like to fetch everything and then map to entries.  I'm trying something simple like this but it crashes:

```
let client = Client(spaceId: spaceId, accessToken: accessToken) 
let query = Query() 
client.fetchMappedEntries(matching: query) { result in 
print("COMPLETION") 
}
```
Am I attempting to use 'MixedMappedArrayResponse' or `MappedArrayResponse` correctly? 

What kind of query do I create to get everything and then use your automatic mapping methods to the `EntryDecodable` models?

**Comment by loudmouth** [comment]
Hey there.

The client object must be passed in the type information via the it's initializer like so, otherwise the SDK will crash as it will attempt to pull contextual information about the relevant content type classes but will be unable to find it:

```swift
let client = Client(spaceId: spaceId,
                    accessToken: accessToken,
                    contentTypeClasses: [Cat.self, Dog.self, Bird.self, Whatever.self])
```

Now that the client has the relevant classes passed in, you can fetch mapped entries:

```swift
client.fetchMappedEntries(matching: Query()) { ... }
```

**Comment by loudmouth** [comment]
Closing as this conversation is continued at support.contentful.com and question has been addressed.
