### ISSUE TITLE
Default date formatter fails to parse date in EntryDecodable models

### ISSUE THREAD

**Issue by kedio** [contentful/contentful.swift#188]
> - contentful.swift version number: 1.0.1
> - Xcode version number: 9.3
> - Target operating system(s) and version number(s)
    - [X ] iOS: 
    - [ ] tvOS: 
    - [ ] watchOS:
    - [ ] macOS:
> - Package manager:
    - [X ] Carthage
    - [ ] Cocoapods

When fetching entries which have a date in their model (using EntryDecodable), the default date formatter fails to parse the date.

So trying to `fetchMappedEntry` using this model.

```
final class ContentfulTournament: EntryDecodable, ResourceQueryable, Tournament {
    static var contentTypeId = "tournament"
    
    let sys: Sys
    let startDate: Date

    required init(from decoder: Decoder) throws {
        sys = try decoder.sys()
        
        let fields = try decoder.contentfulFieldsContainer(keyedBy: Fields.self)
        startDate = try fields.decode(Date.self, forKey: .startDate)
    }
}

extension ContentfulTournament {
    enum Fields: String, CodingKey {
        case startDate
    }
}
```

Would fail with error: 
```
The SDK was unable to parse the JSON: dataCorrupted(Swift.DecodingError.Context(codingPath: [_JSONKey(stringValue: \"Index 0\", intValue: 0), Fields(stringValue: \"startDate\", intValue: nil)], debugDescription: \"Date string does not match format expected by formatter.\", underlyingError: nil))
```

But getting the date string and parsing it would give the expected result.

```
final class ContentfulTournament: EntryDecodable, ResourceQueryable, Tournament {
    static var contentTypeId = "tournament"
    
    let sys: Sys
    let startDate: Date

    required init(from decoder: Decoder) throws {
        sys = try decoder.sys()
        
        let fields = try decoder.contentfulFieldsContainer(keyedBy: Fields.self)
        let startDateString = try fields.decode(String.self, forKey: .startDate)

        let formatter = DateFormatter()
        formatter.dateFormat = "yyyy-MM-dd'T'HH:mmZ"
        startDate = formatter.date(from: startDateString)!
    }
}

extension ContentfulTournament {
    enum Fields: String, CodingKey {
        case startDate
    }
}
```

The date string recieved: `2018-05-05T08:30-03:00`

Should this work out of the box?
Is it possible to change the client date formatter?

**Comment by loudmouth** [comment]
Hey Kevin,

You should be able to change the formatter by doing the following:

```
self.client.jsonDecoder.dateDecodingStrategy = .formatted(yourFormatter)
```

**Comment by loudmouth** [comment]
How did you push that data format into the API? Via the web-app or the CMA?

**Comment by kedio** [comment]
The entry was created using the web-app dashboard by defining a content model with a date and creating an entry using that model.
I will try to change the formatter using your solution.

**Comment by kedio** [comment]
Globally changing the dateDecodingStrategy does not work it fails to parse the createdAt date. So it seems I receive different date format between createdAt and content models dates. 

I have tried changing the date settings in the model between "Date only", "Date and time without timezone" and "Date and time with timezone" but it seems to be UI related only I receive the same value for each setting.

**Comment by loudmouth** [comment]
Hi @kedio would you be able to open a support request with support.contentful.com?

This was why I asked about the date format—because it differs from the format the API uses for system properties. I think the best solution would be to make your field's date format consistent so that the date formatter does not need any special handling.

WDYT?

**Comment by kedio** [comment]
Is it possible to change the field's date format from the web-app (I tried to look to no available) or is this why you suggest opening a support request?

**Comment by loudmouth** [comment]
Yes it should be possible but I am not the best to support there which is why I am suggesting opening a request. Maybe tell them specifically, “date field had date formatted differently then system `createdAt` and `updatedAt`. While the CMA actually allows any date format, the web app _should_ use the same format as our system date properties. Sounds like this could be a ticket for our front end web team

**Comment by loudmouth** [comment]
Turns out I jumped the gun in my earlier comments. 

The Contentful APIs accept any ISO8601 variant, but unfortunately for us Cocoa developers `DateFormatter` only allows one specific format to be (de)serialized at a time. Even the additions of `JSONDecoder.DateDecodingStrategy.iso8601` and the type `ISO8601DateFormatter` from Apple only handle one specific variant of ISO8601. The SDK should be able to handle those variants that the `sys` properties of Contentful resources have in addition to the formats that the Contentful web app enables.

It looks like the best way forward is to use the `JSONDecoder.DateDecodingStrategy.custom`case which takes a function with signature: `(Decoder) throws -> Date`—this function should handle the internet date time stamp variant and the Contentful web app variants of IS8601. [This StackOverflow answer](https://stackoverflow.com/a/46538676/4068264) gives an example of how to do this.

The good news for now is that the SDK does expose the `JSONDecoder` so if other users run into this issue before it's fixed, they can always implement their own function for deserializing dates.

**Comment by kedio** [comment]
Hi @loudmouth , sorry for the delay I just had the chance to update to v2.0.1 and try the variableISO8601Strategy. I was able to decode my objects directly without any modifications to the decoder. Nice! 

But I get unexpected results. It seems to be TimeZone related because I get the right date one day earlier when the time is set to 00:00. I dived a bit into the code and I think it may be related to this [part.](https://github.com/contentful/contentful.swift/blob/bcf2808cf2a51543fc3a755663b47d67c3a1b42e/Sources/Contentful/Date.swift#L58) 

The loop will stop with the first successful format, but the least specific format ("yyyy-MM-dd") seems to be one of the first in the list so it will most likely parse the date using "yyyy-MM-dd" and discard the TimeZone value.

Let me know what you think!

**Comment by kedio** [comment]
I don't know if it can help but I use this to get the expected behavior.
```
        let formatter = DateFormatter()
        formatter.dateFormat = "yyyy-MM-dd"
        let formatterWithTimeZone = DateFormatter()
        formatterWithTimeZone.dateFormat = "yyyy-MM-dd'T'HH:mmZ"

        let startDateString = try fields.decode(String.self, forKey: .startDate)
        let endDateString = try fields.decode(String.self, forKey: .endDate)

        startDate =  formatter.date(from: startDateString) ?? formatterWithTimeZone.date(from: startDateString)
        endDate = formatter.date(from: endDateString) ?? formatterWithTimeZone.date(from: endDateString)
```
Now that I look at it, I seem to be doing the same thing and dateFormat of "yyyy-MM-dd" will fail when parsing a date on the format "yyyy-MM-dd'T'HH:mmZ".

Then maybe it is juste the missing 'Z' [there](https://github.com/contentful/contentful.swift/blob/bcf2808cf2a51543fc3a755663b47d67c3a1b42e/Sources/Contentful/Date.swift#L22).

**Comment by kedio** [comment]
I just got a case this morning that use "yyyy-MM-dd'T'HH:mm". So both "yyyy-MM-dd'T'HH:mm" and "yyyy-MM-dd'T'HH:mmZ" are possible format returned by Contenful api!

**Comment by loudmouth** [comment]
Hey @kedio 

I think for us to find the right solution, we should elaborate more on the specifics of the current problem you're experiencing:
> It seems to be TimeZone related because I get the right date one day earlier when the time is set to 00:00. 

Would you be able to open a new issue and go into more detail: what would help me is if you give an example of the raw datestring(s) you're getting from the Contentful API along with what you expect your date to look like, and what your actually observing. This will help me write some test cases and we can iterate on making this solution more robust.
