### ISSUE TITLE
Query relation depth

### ISSUE THREAD

**Issue by KieranLafferty** [contentful/contentful.swift#267]
- contentful.swift version number:  4.2.4
- Xcode version number: 10.1
- Target operating system(s) and version number(s)
  - [x] iOS: 
  - [ ] tvOS: 
  - [ ] watchOS:
  - [ ] macOS:
- Package manager:
  - [ ] Carthage
  - [x] Cocoapods

I'm having an issue where I'm fetching a object by ID using `fetch(_, id:)` whereby I need a 3rd degree relationship from my object similar to the below

```
- title: ContentTitle (i.e. The Simpsons)
  - collections: [ContentVideoCollection (i.e. Season 1)]
    - videos: [ContentVideo (i.e. Episode 1, 2, 3, etc)]
      - video: Contentful.Asset
```

I'm finding that the ContentTitle and ContentVideoCollection come back successfully, however the array of videos on ContentVideoCollection of type ContentVideo is coming back nil (presumably due to some depth limiting)

I was wondering if there is a way to increase the depth of the query?

**Comment by loudmouth** [comment]
You can use either the static or instance method `include` to increase the query depth:

See [here](https://github.com/contentful/contentful.swift/blob/master/Sources/Contentful/Query.swift#L352) and [here](https://github.com/contentful/contentful.swift/blob/master/Sources/Contentful/Query.swift#L369)

**Comment by manmal** [comment]
@KieranLafferty Has your issue been resolved with the information we provided?

**Comment by KieranLafferty** [comment]
Yes this is great thank you!

**Comment by KieranLafferty** [comment]
Actually, after taking a second look at my implementation this only works for queries. In my particular case I am doing a fetch by ID as follows: 

```
 self.contentfulClient.fetch(
            ContentTitle.self,
            id: self.titleID
        ) { (result) }
```
I suppose I could do a query where ID = <some_id> and take the first result as a workaround. Is there a more specific solution for doing a fetch by id?

**Comment by manmal** [comment]
A query with the `id` set would _currently_ be the preferred way to achieve your desired behavior, to my best of my knowledge. But I do agree with you that the ability to specify the includes level in `Client.fetch(_:id:then:)` would be preferrable. I'll think a bit more about this and probably add a parameter to the `fetch` method today - I think it could be merged to `master` by tomorrow, or next week at the latest.

To provide some background info: 
As can be seen in [Client.swift:476](https://github.com/contentful/contentful.swift/blob/master/Sources/Contentful/Client.swift#L476), `Client.fetch(_:id:then:)` does indeed build a `ResourceQuery` and calls `completion` with the first value, if any is returned. Since the query is not modified via `.include(_:)`, no `include` parameter is added to the API call, and the API falls back to a include level of 1 (described [here](https://www.contentful.com/developers/docs/references/content-delivery-api/#/reference/links/retrieval-of-linked-items)).
@KieranLafferty
