### ISSUE TITLE
How to get tests working, almost all fail

### ISSUE THREAD

**Issue by basememara** [contentful/contentful.swift#298]
- contentful.swift version number: 5.0.9
- Xcode version number: 11
- Target operating system(s) and version number(s)
  - [x] iOS: 
  - [ ] tvOS: 
  - [ ] watchOS:
  - [ ] macOS:
- Package manager:
  - [x] Carthage
  - [ ] Cocoapods

Is there something special I have to do to get the tests working? I ran `carthage bootstrap` and compiled, but many of the tests fail. Also the carthage resolve/private files are malformed and had to manually fix it.

<img width="391" alt="image" src="https://user-images.githubusercontent.com/892152/79896232-195d3400-83d6-11ea-88b0-41518beb7e18.png">

**Comment by matelo** [comment]
hey @basememara 
Thanks for pointing out! You are right, problem was with corrupted Carthage files. We have fixed those and reinstalled dependencies, it should work now.
Fixed in https://github.com/contentful/contentful.swift/pull/299

In meantime, you can locally fix .private and .resolved files, using `OHHTTPStubs` in version 8.0.0. Then delete `Carthage` folder and run `carthage bootstrap ` again. Tests should pass again
