### ISSUE TITLE
Searching on one-to-many references doesn't work

### ISSUE THREAD

**Issue by 6franek** [contentful/contentful.swift#31]
I have a problem with searching on "one-to-many" references fields. I have two Content Types: `flyer` and `shop`. In `flyer` Content Type there is a field named `shops` which is a "one-to-many" references field (referencing `shop` content type).  I would like to find all `flyer`s which have `shop` with specific names referenced to them in a `shops` field. I do it by adding following parameters to the `fetchEntries` function:
```
let parameters = ["content_type": "flyer", "fields.shops.sys.contentType.sys.id": "shop", "fields.shops.fields.name[all]": "Warszawa"]
```
Unfortunately I get this error:
```
The operation couldn’t be completed. (Contentful.ContentfulError error 1.)
```

I have made a test and added a field `one_shop` to `flyer`s content type and searching on one-to-one references seems to be working fine.

Am I doing something wrong or searching on one-to-many references is not supported? I am confused, because [this blog post](https://www.contentful.com/r/knowledgebase/searching-on-references/) states that it should work, but [in the content delivery API docs](https://www.contentful.com/developers/docs/references/content-delivery-api/#/reference/search-parameters/search-on-references) it is written that :
> You can only search on references on fields which link to a single entry. Fields which hold references to many entries or fields with references to assets are not supported.

Which information is correct?

**Comment by loudmouth** [comment]
Hey @6franek . I'll make sure to look into this tomorrow. I've been sick the past few days and unable to get work done.

**Comment by loudmouth** [comment]
@6franek, apologies for the delayed response.

The latter information you posted is the correct one. At current, relational queries are not supported. To achieve what you want, I recommend querying with the `include` parameter ([see API reference](https://www.contentful.com/developers/docs/references/content-delivery-api/#/reference/links/query-entries)) and then filtering for the specific client-side:

```
let parameters = ["content_type": "flyer", "include": 1]
```

**Comment by lmf-git** [comment]
> Hey @6franek . I'll make sure to look into this tomorrow. I've been sick the past few days and unable to get work done.

Seeing how this gets ignored and then seeing personal excuses is so deeply disappointing.

**Comment by loudmouth** [comment]
I no longer work for Contentful, but the original question in this issue was answered at the time: https://github.com/contentful/contentful.swift/issues/31#issuecomment-276603977

The API did not support searching related entries by their encapsulated data at the time for one-to-many relationships. 

The original poster of this issue quotes the docs as asked for clarification about some potentially contradictory info in the API doc, or the blog post. The API docs were referenced in both the original issue, and the closing comment. See them pasted below.

> Restrictions
Searching on references has the following restrictions:
> You can only search on references on fields which link to a single entry. Fields which hold references to many entries or fields with references to assets are not supported.
> The maximum number of reference searches in one query is 2. A larger value will return an error.

https://www.contentful.com/developers/docs/references/content-delivery-api/#/reference/search-parameters/search-on-references

This seems to still be the state of the API and so the closing comment gives a workaround to fetch all related entries and then do client-side filtering.
