### ISSUE TITLE
The framework contains disallowed file

### ISSUE THREAD

**Issue by woxtu** [contentful/contentful.swift#7]
Hi,

I got the following error when submitting the app to iTunes:

```
ERROR ITMS-90206: "Invalid Bundle. The bundle at '***.app/Frameworks/Contentful.framework' contains disallowed file 'Frameworks'."
```

It seems that `Contentful.framework` contains unnecessary frameworks.

Carthage 0.16.2, Xcode 7.3

**Comment by neonichu** [comment]
Interesting, it was build with `carthage archive` so I assumed it'll work fine — will investigate and report back to you.

**Comment by neonichu** [comment]
Sorry for the delay in dealing with this, but I have now updated the release build in <https://github.com/contentful/contentful.swift/releases/tag/0.2.1> and also disabled embedding Swift libs in the project (see 05900166a8dbea6606603bc2331153753ea2c9d8) so that future releases also won't have this problem.

**Comment by woxtu** [comment]
Looks good to me. Thank you!
