### ISSUE TITLE
Contentful.Entry.fields does not contain empty fields

### ISSUE THREAD

**Issue by abakhtin** [contentful/contentful.swift#85]
> - contentful.swift version number: 0.6.0
> - Xcode version number: 8.3.2
> - Target operating system(s) and version number(s)
    - [x] iOS: 
    - [ ] tvOS: 
    - [ ] watchOS:
    - [ ] macOS:
> - Package manager:
    - [x] Carthage
    - [ ] Cocoapods

Hi,

After updating of field to empty value we do not get fields with empty value. 
It's very important after update of entry in coredata. We do not want to recreate fully entry - just update fields we receive. 

I believe it should return nil value even for not presented values.

Thanks in advance.

**Comment by loudmouth** [comment]
contentful.swift is meant to interface only with Contentful's [Content Delivery API](https://www.contentful.com/developers/docs/references/content-delivery-api/) which is read-only. Any state you change locally in either memory, CoreData, or another local database will not be propagated to Contentful's hosted storage. In order to change the values of fields, you should visit [app.contentful.com](https://app.contentful.com) to edit and manage your content.

While there is a [Content Management API](www.contentful.com/developers/docs/references/content-management-api), there is currently no Swift SDK available for interfacing with it—it is on the roadmap, but probably won't be published for at least several more months. There is an [Objective-C SDK for the management API](https://cocoapods.org/pods/ContentfulManagementAPI), but it will require that you also integrate the Objective-C Delivery SDK and there are no plans to implement new features for interacing with the Contentful API's in the objective-c toolchain.

**Comment by abakhtin** [comment]
@loudmouth sorry for misunderstanding from me.

The problem is if the property is not set on the contentful server side - we do not receive it in fields array of entry. 
Does it make sense?

**Comment by loudmouth** [comment]
Hey @abakhtin,

Just to clarify to make sure I understand correctly: are you saying that if you have a field on an `Entry`, let's say a String `title` on your Entry model, and it's value is `nil` in Contentful's database, that it is not being returned in the fields array?

If this is your question, then this is expected behavior of the API. the JSON payload returned by the Contentful API omits fields that have no value. As fields is simply a dictionary of field names and values, a check like so for a field with an absent value should return nil:

```
let myTitleString: String? = fields["myKey"] as? String
```

You can read more about empty fields in the Contentful documentation [here](https://www.contentful.com/r/knowledgebase/localization/#empty-fields). If you scroll up a small bit, you will see a table describing the same behavior I just mentioned above.

**Comment by abakhtin** [comment]
@loudmouth Thanks for clarifing, you understand correctly. Sorry for missing documentation. 

Don't you think that it is great to send nil instead of empty to show that data is nil and not absent?
Seems like it is default behavior for json serializers.

**Comment by loudmouth** [comment]
I think it's common practice to omit absent fields in API responses. Also, it is illegal to store `nil` as a value in in an Objective-C `NSDictionary`—the system will crash if this is done. 

If were restricted to only working in pure swift and wanted to add nil to our `fields: [String: Any]` Swift dictionary, we would have to change the type to `fields: [String: Any?]` with the optional modifier added so that nil could be qualified as a valid value. This would make retrieving values from fields dictionary more cumbersome.

Regarding this point:
> Seems like it is default behavior for json serializers.

If the JSON (essentially a dictionary) doesn't have the field, and the SDK is simply populating a `fields`dictionary, there is no way to know which absent key should be inserted just so that a `nil` value can be stored. While converting to your own model classes, it is the SDK consumer's responsibility to nullify optional fields when not present in `fields`.
